### PR TITLE
Enables reported language to be configurable and delayed naming of transaction

### PR DESCRIPTION
**Pull request by jolson88**
We ran into some issues we needed to fix when using this library in our own code-base:
- The "python" as default language was causing reporting issues in our dashboard (as if you already have the same app name with a different language like nodejs, it will cause a new app dashboard like "APP_NAME (Python)" to be created rather than using existing dashboard). This allows the user to specify the language they want transactions reported as a setting instead of always using Python.
- We are not using Phoenix, we are using raw Plugs + Cowboy. Because of the ordering of the plugs, we can't specify the name of the transaction when the NewRelic plug is first called (as we pull the transaction name out of a variable set in conn.assign by the method executed in the router). We can retrieve this value before the response is sent, so when finish transaction is called. This PR makes the change backward-compatible by keeping the existing methods but simply providing a way to update the name of the transaction (via the new `name/2` method) before calling finish.

Feedback is welcome of course :).

### CODE REVIEW

**Comment by romul** [comment]
Hello, @jolson88! This is your first Pull Request that will be reviewed by [Ebert](https://ebertapp.io/), an automatic Code Review service. It will leave comments on this diff with potential issues and style violations found in the code as you push new commits. You can also see all the issues found on this Pull Request on its [review page](https://ebertapp.io/github/romul/newrelic.ex/pulls/3). Please check our [documentation](https://ebertapp.io/docs) for more information.

**Comment by jolson88** [comment]
Hey @romul! Is there anything I can do or need to do to help out with getting this merged if possible? I'd love to switch our code back to using your official library vs. our own custom fork :).

**Comment by romul** [comment]
Hey @jolson88! Thank you for the contributions and sorry for the late reply. 
I've started to move your commits to the master.
As to `name` function.. I'd prefer to see it more like
```
  @spec name(t, String.t) :: t
  def update_name(transaction, new_name) do
    %{transaction | name: new_name}
  end
```

In this case: 
the function name is more specific, 
the first arg - is the main one (Elixir convention) 
and there's no need in destructuring of `transaction` (maybe will be more fields in this struct in the future).

**Comment by romul** [comment]
Btw, I'm ok with making phoenix dependency optional. So help in this direction is also appreciated.

**Comment by jolson88** [comment]
I like those ideas! I'll go ahead and make the changes later today.

**Comment by jolson88** [comment]
Okay, changes made and pushed back up. Thanks again!

**Comment by romul** [comment]
@jolson88 Merged! And the version 0.1.1 with your changes has been also released.
Thank you again for the help.

**Comment by jolson88** [comment]
Thanks romul! You betcha!

**Pull request closed without merging**
